-- COMPREHENSIVE REMEDIATION SQL FOR SWASTIK MEDICARE
-- 1. Schema Core Updates (Marketplace & Partner Features)
-- 2. Security Hardening (RLS & Access Control)

BEGIN;

-- ==========================================
-- PHASE 1: SCHEMA UPDATES
-- ==========================================

DO $$ 
BEGIN 
    -- Add Product columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isOTC') THEN
        ALTER TABLE "Product" ADD COLUMN "isOTC" BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isScheduleH1') THEN
        ALTER TABLE "Product" ADD COLUMN "isScheduleH1" BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='brand') THEN
        ALTER TABLE "Product" ADD COLUMN "brand" TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='salt') THEN
        ALTER TABLE "Product" ADD COLUMN "salt" TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='discount') THEN
        ALTER TABLE "Product" ADD COLUMN "discount" DOUBLE PRECISION DEFAULT 0.0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isRecommended') THEN
        ALTER TABLE "Product" ADD COLUMN "isRecommended" BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isColdChain') THEN
        ALTER TABLE "Product" ADD COLUMN "isColdChain" BOOLEAN DEFAULT false;
    END IF;
    
    -- Add User columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='phoneVerified') THEN
        ALTER TABLE "User" ADD COLUMN "phoneVerified" BOOLEAN DEFAULT false;
    END IF;
END $$;

-- Marketplace Tables
CREATE TABLE IF NOT EXISTS "SubOrder" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "retailerId" TEXT NOT NULL,
    "userId" TEXT,
    "items" JSONB NOT NULL,
    "total" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "SubOrder_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "DraftInvoice" (
    "id" TEXT NOT NULL,
    "subOrderId" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "adminRemarks" TEXT,
    "rejectionReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "DraftInvoice_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "MedicinePriceMemory" (
    "id" TEXT NOT NULL,
    "medicineName" TEXT NOT NULL,
    "genericName" TEXT,
    "price" DOUBLE PRECISION NOT NULL,
    "lastRetailerId" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "MedicinePriceMemory_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "MedicinePriceMemory_medicineName_key" ON "MedicinePriceMemory"("medicineName");

CREATE TABLE IF NOT EXISTS "SubstitutionRule" (
    "id" TEXT NOT NULL,
    "sourceMedicine" TEXT NOT NULL,
    "substituteGeneric" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SubstitutionRule_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "SubstitutionRule_sourceMedicine_key" ON "SubstitutionRule"("sourceMedicine");

CREATE TABLE IF NOT EXISTS "DeliveryAssignment" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Assigned',
    "distance" DOUBLE PRECISION,
    "estimatedTime" TEXT,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "DeliveryAssignment_pkey" PRIMARY KEY ("id")
);

-- ==========================================
-- PHASE 2: SECURITY HARDENING (RLS)
-- ==========================================

-- Enable RLS
ALTER TABLE IF EXISTS public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Prescription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Retailer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."WalletTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Withdrawal" ENABLE ROW LEVEL SECURITY;

-- Baseline Policies
DROP POLICY IF EXISTS "Users can view their own profile" ON public."User";
CREATE POLICY "Users can view their own profile" ON public."User" FOR SELECT USING (id = current_setting('request.jwt.claims', true)::jsonb->>'sub');

DROP POLICY IF EXISTS "Users can view their own orders" ON public."Order";
CREATE POLICY "Users can view their own orders" ON public."Order" FOR SELECT USING ("userId" = current_setting('request.jwt.claims', true)::jsonb->>'sub');

DROP POLICY IF EXISTS "Admins can view all orders" ON public."Order";
CREATE POLICY "Admins can view all orders" ON public."Order" FOR SELECT USING (
  EXISTS (SELECT 1 FROM public."User" WHERE id = current_setting('request.jwt.claims', true)::jsonb->>'sub' AND role = 'ADMIN')
);

DROP POLICY IF EXISTS "Public can view verified retailers" ON public."Retailer";
CREATE POLICY "Public can view verified retailers" ON public."Retailer" FOR SELECT USING (verified = true);

-- Force RLS for sensitive tables
ALTER TABLE public."WalletTransaction" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."Withdrawal" FORCE ROW LEVEL SECURITY;

COMMIT;
