-- Remediation SQL for Swastik Medicare Marketplace
-- Adds missing columns and tables to ensure production DB matches current Prisma schema

BEGIN;

-- 1. Updates to Existing Tables
DO $$ 
BEGIN 
    -- Add Product columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isOTC') THEN
        ALTER TABLE "Product" ADD COLUMN "isOTC" BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isScheduleH1') THEN
        ALTER TABLE "Product" ADD COLUMN "isScheduleH1" BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isColdChain') THEN
        ALTER TABLE "Product" ADD COLUMN "isColdChain" BOOLEAN DEFAULT false;
    END IF;
    
    -- Add User columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='phoneVerified') THEN
        ALTER TABLE "User" ADD COLUMN "phoneVerified" BOOLEAN DEFAULT false;
    END IF;
END $$;

-- 2. New Marketplace Tables

CREATE TABLE IF NOT EXISTS "SubOrder" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "retailerId" TEXT NOT NULL,
    "userId" TEXT,
    "items" JSONB NOT NULL,
    "total" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "SubOrder_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "DraftInvoice" (
    "id" TEXT NOT NULL,
    "subOrderId" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "adminRemarks" TEXT,
    "rejectionReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "DraftInvoice_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "MedicinePriceMemory" (
    "id" TEXT NOT NULL,
    "medicineName" TEXT NOT NULL,
    "genericName" TEXT,
    "price" DOUBLE PRECISION NOT NULL,
    "lastRetailerId" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "MedicinePriceMemory_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "MedicinePriceMemory_medicineName_key" ON "MedicinePriceMemory"("medicineName");

CREATE TABLE IF NOT EXISTS "SubstitutionRule" (
    "id" TEXT NOT NULL,
    "sourceMedicine" TEXT NOT NULL,
    "substituteGeneric" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SubstitutionRule_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "SubstitutionRule_sourceMedicine_key" ON "SubstitutionRule"("sourceMedicine");

CREATE TABLE IF NOT EXISTS "DeliveryAssignment" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Assigned',
    "distance" DOUBLE PRECISION,
    "estimatedTime" TEXT,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "DeliveryAssignment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "WebhookConfig" (
    "id" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "secret" TEXT,
    "events" TEXT[],
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "WebhookConfig_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "AdminApprovalLog" (
    "id" TEXT NOT NULL,
    "adminId" TEXT NOT NULL,
    "actionType" TEXT NOT NULL,
    "targetId" TEXT NOT NULL,
    "details" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AdminApprovalLog_pkey" PRIMARY KEY ("id")
);

-- Foreign Keys (Optional but recommended for strictness)
-- Note: Using Prisma client is generally safer for relations, but adding FKs here ensures DB integrity.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='SubOrder_orderId_fkey') THEN
        ALTER TABLE "SubOrder" ADD CONSTRAINT "SubOrder_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;
END $$;

COMMIT;
