import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";

// ============================================================================
// AI MARKETING, VIDEO, POST & PROMOTION INTELLIGENCE API
// Direct Connection with Customer Finding & Supplier Finding Intelligence
// ============================================================================

export async function GET(req) {
    try {
        const session = await getServerSession(authOptions);
        if (!session || !["ADMIN", "SUPER_ADMIN", "CRM_STAFF"].includes(session.user?.role)) {
            return NextResponse.json({ error: "Unauthorized access" }, { status: 401 });
        }

        const { searchParams } = new URL(req.url);
        const action = searchParams.get("action");

        // 1. Fetch KPI Overview & Active Campaigns
        const campaigns = await prisma.marketingCampaign.findMany({
            include: {
                contents: true,
                leads: true,
                insights: true
            },
            orderBy: { createdAt: "desc" }
        });

        // 2. Fetch All Scheduled & Published Content
        const allContents = await prisma.marketingContent.findMany({
            include: { campaign: true },
            orderBy: { createdAt: "desc" }
        });

        // 3. Fetch All Inbound Leads generated by marketing
        const marketingLeads = await prisma.marketingLead.findMany({
            include: { campaign: true },
            orderBy: { createdAt: "desc" }
        });

        // 4. Fetch Insights
        const insights = await prisma.marketingInsight.findMany({
            include: { campaign: true },
            orderBy: { createdAt: "desc" }
        });

        // Calculate Aggregate KPI Metrics from real DB data
        const totalImpressions = allContents.reduce((acc, c) => acc + (c.impressions || 0), 0);
        const totalViews = allContents.reduce((acc, c) => acc + (c.views || 0), 0);
        const totalClicks = allContents.reduce((acc, c) => acc + (c.clicks || 0), 0);
        const totalEnquiries = allContents.reduce((acc, c) => acc + (c.enquiries || 0), 0);
        const totalLeads = marketingLeads.length;
        const totalOrders = marketingLeads.filter(l => l.status === "CONVERTED_ORDER" || l.status === "REPEAT_CUSTOMER").length;
        const totalRevenue = marketingLeads.reduce((acc, l) => acc + (l.lifetimeRevenue || l.firstOrderValue || 0), 0);
        const totalBudgetSpent = campaigns.reduce((acc, c) => acc + (c.spent || 0), 0);
        const avgCpl = totalLeads > 0 && totalBudgetSpent > 0 ? `₹${(totalBudgetSpent / totalLeads).toFixed(2)}` : null;
        const conversionRate = totalLeads > 0 ? `${((totalOrders / totalLeads) * 100).toFixed(1)}%` : null;

        // Compute real channel breakdown from actual marketing leads in DB
        const channelMap = {};
        for (const lead of marketingLeads) {
            const ch = lead.sourceChannel || "UNKNOWN";
            if (!channelMap[ch]) channelMap[ch] = { leads: 0, orders: 0, revenue: 0, reach: 0 };
            channelMap[ch].leads += 1;
            if (lead.status === "CONVERTED_ORDER" || lead.status === "REPEAT_CUSTOMER") channelMap[ch].orders += 1;
            channelMap[ch].revenue += (lead.lifetimeRevenue || lead.firstOrderValue || 0);
        }
        for (const ch of Object.keys(channelMap)) {
            const spent = campaigns
                .filter(c => c.campaignType && c.campaignType.includes(ch))
                .reduce((s, c) => s + (c.spent || 0), 0);
            const rev = channelMap[ch].revenue;
            channelMap[ch].roas = spent > 0 ? `${(rev / spent).toFixed(1)}x` : "Organic";
        }
        const channelBreakdown = Object.keys(channelMap).length > 0 ? channelMap : {};

        // Compute top channel by lead count
        const topChannelEntry = Object.entries(channelMap).sort((a, b) => b[1].leads - a[1].leads)[0];
        const topChannel = topChannelEntry ? topChannelEntry[0] : null;

        return NextResponse.json({
            success: true,
            kpis: {
                activeCampaigns: campaigns.filter(c => c.status === "ACTIVE").length,
                totalReach: totalImpressions,
                totalViews,
                totalClicks,
                totalEnquiries,
                totalLeads,
                totalOrders,
                totalRevenue,
                totalBudgetSpent,
                avgCpl,
                conversionRate,
                topChannel,
                topGeography: null,
                topProduct: null
            },
            campaigns,
            contents: allContents,
            leads: marketingLeads,
            insights,
            channelBreakdown
        });
    } catch (error) {
        console.error("Marketing Intelligence GET Error:", error);
        return NextResponse.json({ error: "Failed to fetch marketing intelligence data" }, { status: 500 });
    }
}

export async function POST(req) {
    try {
        const session = await getServerSession(authOptions);
        if (!session || !["ADMIN", "SUPER_ADMIN", "CRM_STAFF"].includes(session.user?.role)) {
            return NextResponse.json({ error: "Unauthorized access" }, { status: 401 });
        }

        const body = await req.json();
        const { action } = body;

        // =====================================================================
        // ACTION 1: AI CONTENT CREATION & MULTI-CHANNEL ADAPTATION AGENT
        // =====================================================================
        if (action === "create_ai_campaign") {
            const {
                title,
                objective = "PRODUCT_SALES",
                productOrService = "Swastik Chronic Care & Medicine Delivery",
                targetAudienceGroup = "NEW_PROSPECTS",
                geographyCity = "Gorakhpur",
                geographyRadiusKm = 15,
                campaignType = "HYBRID",
                budget = 1500
            } = body;

            // 1. Determine Paid Recommendation
            let paidRecommendation = "TEST_FIRST";
            if (budget > 3000 && (objective === "LEAD_GEN" || objective === "B2B_SUPPLIER")) {
                paidRecommendation = "PROMOTE";
            } else if (budget < 500) {
                paidRecommendation = "DO_NOT_PROMOTE";
            }

            // 2. Create the Campaign Record
            const campaign = await prisma.marketingCampaign.create({
                data: {
                    title: title || `AI Campaign: ${productOrService} (${geographyCity})`,
                    objective,
                    productOrService,
                    campaignType,
                    targetAudienceGroup,
                    geographyCity,
                    geographyRadiusKm: parseFloat(geographyRadiusKm),
                    budget: parseFloat(budget),
                    spent: 0.0,
                    paidRecommendation,
                    paidApprovalStatus: "PENDING",
                    status: "PENDING_APPROVAL"
                }
            });

            // 3. Generate Adapted Content for Each Channel
            const contentsToGenerate = [
                {
                    contentType: "SHORT_VIDEO",
                    channel: "INSTAGRAM",
                    title: `Reel: Never Run Out of ${productOrService} in ${geographyCity}`,
                    keyMessage: `Fast 3-hour doorstep delivery + flat 10% instant discount with certified pharmacy trust.`,
                    scriptOrCopy: `[HOOK - 0 to 3s]: Still standing in long medical store queues in ${geographyCity}?\n\n[STORY - 4 to 12s]: Meet Swastik Medicare. Upload your prescription or search over 20,000+ allopathy, homeopathy, and ayurvedic medicines from verified local stores.\n\n[OFFER - 13 to 20s]: Get genuine medicines delivered to your doorstep in under 3 hours with tamper-evident packaging!\n\n[CTA - 21 to 30s]: Tap the link below to order now and get flat ₹100 off your first delivery!`,
                    visualPrompt: `High energy vertical 9:16 video showing a smiling delivery rider arriving in front of a modern home in ${geographyCity}, handing a securely sealed medical package. Clean UI overlays showing "3-Hour Delivery" and "100% Genuine Medicine".`,
                    callToAction: "Order Now on SwastikMed.online",
                    targetAudience: targetAudienceGroup,
                    targetGeography: `${geographyCity} (+${geographyRadiusKm}km)`
                },
                {
                    contentType: "EDUCATIONAL_VIDEO",
                    channel: "YOUTUBE",
                    title: `Complete Guide: How to Save 20-30% on Monthly Medicines in ${geographyCity}`,
                    keyMessage: `Explaining generic substitutes, licensed quality assurance, and home delivery convenience.`,
                    scriptOrCopy: `[INTRO]: Hello everyone! In this video, we're breaking down how families in Eastern UP and ${geographyCity} are cutting their monthly medicine bills by up to 30% without compromising on salt quality...\n\n[MAIN CHAPTER 1 - Understanding Verified Salt Substitutes]: When prescribed branded meds, pharmacists often don't show you clinical-grade certified alternatives that cost half the price...\n\n[MAIN CHAPTER 2 - How Hyperlocal Routing Works]: Swastik Medicare connects you directly to the nearest licensed pharmacy within 5km, guaranteeing fresh batch delivery...\n\n[OUTRO & CTA]: Check out SwastikMed.online today. Like, subscribe, and download our app for free health reminders!`,
                    visualPrompt: `Professional horizontal 16:9 explainer video with animated infographs comparing medicine MRP vs generic equivalent savings, with doctor endorsement badges.`,
                    callToAction: "Visit swastikmed.online/shop-medicines",
                    targetAudience: "Families, Caregivers & Chronic Patients",
                    targetGeography: `${geographyCity} & Eastern UP`
                },
                {
                    contentType: "WHATSAPP_OFFER",
                    channel: "WHATSAPP",
                    title: `Exclusive VIP WhatsApp Offer: ${productOrService}`,
                    keyMessage: `Personalized refill notification + free delivery for orders above ₹300.`,
                    scriptOrCopy: `🙏 Namaste from Swastik Medicare!\n\nNeed your monthly refill of *${productOrService}* in ${geographyCity}?\n\n✅ 100% Genuine, Sealed Medicine\n⚡ Superfast 3-Hour Delivery to your doorstep\n💰 Extra 10% Discount on System Price\n\n📲 *Order in 1 Click:* https://www.swastikmed.online/en/shop-medicines\n💬 Or reply with your prescription image right here!`,
                    visualPrompt: `Clean WhatsApp banner image featuring medicine bottle, verified tick mark, and "Free Home Delivery in Gorakhpur" badge.`,
                    callToAction: "Reply 'YES' to Order via WhatsApp",
                    targetAudience: "Existing & Inbound Inquiries",
                    targetGeography: geographyCity
                },
                {
                    contentType: "BUSINESS_POST",
                    channel: "LINKEDIN",
                    title: `Transforming Pharma Supply & Retailer Margin in Tier-2 India`,
                    keyMessage: `Connecting local pharmacies, stockists, and doctors into a unified digital supply grid.`,
                    scriptOrCopy: `How is Swastik Medicare empowering independent retail pharmacies across Eastern UP?\n\nBy deploying our Hyperlocal Routing & Intelligence Grid, local licensed chemist shops are experiencing a 35% surge in daily order fulfillment while eliminating dead stock.\n\nKey Highlights:\n🔹 Automated 10% commission payout via UPI\n🔹 Direct integration with patient prescription uploads\n🔹 End-to-end tamper-evident cold chain delivery\n\nAre you a pharmacy owner or distributor? Partner with us: https://www.swastikmed.online/en/retailer/register`,
                    visualPrompt: `Infographic showcasing Swastik Medicare's Hyperlocal B2B Pharma Network architecture connecting Retailers, Hospitals, and Delivery Agents.`,
                    callToAction: "Register as Pharmacy Partner",
                    targetAudience: "Retailers, Stockists, Pharma Distributors",
                    targetGeography: "Uttar Pradesh & National"
                },
                {
                    contentType: "ARTICLE",
                    channel: "WEBSITE",
                    title: `Everything You Need to Know About Ordering Medicines Online Safely in ${geographyCity}`,
                    keyMessage: `Comprehensive guide covering prescription verification, cold-chain safety, and authentic batch tracking.`,
                    scriptOrCopy: `Healthcare in ${geographyCity} is entering a digital renaissance. With Swastik Medicare, patients no longer need to travel across town to search for specialty allopathy or rare homeopathy dilutions...\n\n### Why Licensed Hyperlocal Matters\nUnlike centralized warehouses that ship medicines from days away, Swastik Medicare routes every order to the nearest verified neighborhood chemist...\n\n### 3 Safety Tips for Online Medicine Orders\n1. Always ensure a valid batch number and expiry date.\n2. Confirm tamper-evident seal integrity.\n3. Keep your doctor's digital prescription on file.\n\nExplore our complete directory of verified doctors, lab tests, and pharmacies at SwastikMed.online.`,
                    visualPrompt: `High-resolution web banner showing modern pharmacy shelf with clean green and medical blue aesthetics.`,
                    callToAction: "Read Full Guide & Browse Medicines",
                    targetAudience: "SEO Organic Searchers",
                    targetGeography: geographyCity
                }
            ];

            // Save all generated content items linked to this campaign
            for (const item of contentsToGenerate) {
                await prisma.marketingContent.create({
                    data: {
                        campaignId: campaign.id,
                        ...item,
                        approvalStatus: "PENDING_APPROVAL", // Strict human approval guardrail
                        isPublished: false
                    }
                });
            }

            // Create Initial AI Performance Insight
            await prisma.marketingInsight.create({
                data: {
                    campaignId: campaign.id,
                    category: "AUDIENCE_RESPONSE",
                    title: `Predicted High Conversion in ${geographyCity}`,
                    insightText: `Targeting "${targetAudienceGroup}" with WhatsApp & Instagram Reel is projected to deliver a Cost Per Lead under ₹35 with 22%+ order conversion.`,
                    whyItHappened: `High smartphone penetration in ${geographyCity} combined with instant 3-hour hyperlocal delivery messaging creates strong impulse trust.`,
                    recommendedAction: `Approve the Instagram Reel and WhatsApp offer first, run a ₹500 test budget, then scale upon hitting 15+ verified customer orders.`
                }
            });

            return NextResponse.json({
                success: true,
                message: "AI Campaign & Multi-Channel Content generated successfully with Human Approval Guardrails.",
                campaignId: campaign.id
            });
        }

        // =====================================================================
        // ACTION 2: HUMAN APPROVAL GUARDRAILS (Content & Paid Budget)
        // =====================================================================
        if (action === "approve_content") {
            const { contentId, approved = true, notes } = body;
            const updated = await prisma.marketingContent.update({
                where: { id: contentId },
                data: {
                    approvalStatus: approved ? "APPROVED" : "REJECTED",
                    approvedBy: session.user.email || session.user.name || "Admin",
                    approvalNotes: notes || (approved ? "Approved by Admin for distribution" : "Rejected/Requires edits")
                }
            });
            return NextResponse.json({ success: true, message: `Content ${approved ? "Approved" : "Rejected"} successfully.`, content: updated });
        }

        if (action === "approve_paid_budget") {
            const { campaignId, approved = true, approvedBudget } = body;
            const updated = await prisma.marketingCampaign.update({
                where: { id: campaignId },
                data: {
                    paidApprovalStatus: approved ? "APPROVED" : "REJECTED",
                    budget: approvedBudget ? parseFloat(approvedBudget) : undefined,
                    status: approved ? "ACTIVE" : "DRAFT",
                    approvedBy: session.user.email || "Admin"
                }
            });
            return NextResponse.json({ success: true, message: `Paid promotion budget ${approved ? "Approved" : "Rejected"}.`, campaign: updated });
        }

        // =====================================================================
        // ACTION 3: PUBLISH CONTENT TO ORGANIC / AUTHORIZED CHANNELS
        // =====================================================================
        if (action === "publish_content") {
            const { contentId, externalPostUrl } = body;
            const content = await prisma.marketingContent.findUnique({ where: { id: contentId } });
            
            if (!content || content.approvalStatus !== "APPROVED") {
                return NextResponse.json({ error: "Content must be explicitly APPROVED by human before publishing." }, { status: 400 });
            }

            const updated = await prisma.marketingContent.update({
                where: { id: contentId },
                data: {
                    isPublished: true,
                    publishedAt: new Date(),
                    externalPostUrl: externalPostUrl || `https://swastikmed.online/marketing/published/${contentId}`
                }
            });

            return NextResponse.json({ success: true, message: "Content published successfully.", content: updated });
        }

        // =====================================================================
        // ACTION 4: LEAD CAPTURE & CONNECTION TO CUSTOMER FINDING INTELLIGENCE
        // =====================================================================
        if (action === "capture_marketing_lead") {
            const {
                fullName,
                phone,
                email,
                businessName,
                customerType = "PATIENT",
                location = "Gorakhpur",
                sourceChannel = "WHATSAPP",
                productInterest = "Chronic Care Medicines",
                campaignId
            } = body;

            if (!fullName || !phone) {
                return NextResponse.json({ error: "Full Name and Phone Number are required." }, { status: 400 });
            }

            // Deduplication Check
            let existingLead = await prisma.marketingLead.findFirst({
                where: { phone: phone.trim() }
            });

            // Calculate AI Lead Score and A/B/C Priority
            let leadScore = 70;
            let priorityRank = "B";

            if (productInterest?.toLowerCase().includes("chronic") || productInterest?.toLowerCase().includes("monthly") || customerType === "RETAILER" || customerType === "STOCKIST") {
                leadScore = 92;
                priorityRank = "A"; // High Priority
            } else if (productInterest?.toLowerCase().includes("general") || productInterest?.toLowerCase().includes("inquiry")) {
                leadScore = 65;
                priorityRank = "B"; // Medium Priority
            } else {
                leadScore = 45;
                priorityRank = "C"; // Low Priority
            }

            let savedLead;
            if (existingLead) {
                // Update existing lead with latest interaction
                savedLead = await prisma.marketingLead.update({
                    where: { id: existingLead.id },
                    data: {
                        productInterest,
                        sourceChannel,
                        leadScore,
                        priorityRank,
                        campaignId: campaignId || existingLead.campaignId,
                        updatedAt: new Date()
                    }
                });
            } else {
                // Create new Marketing Lead
                savedLead = await prisma.marketingLead.create({
                    data: {
                        fullName,
                        phone: phone.trim(),
                        email: email || null,
                        businessName: businessName || null,
                        customerType,
                        location,
                        sourceChannel,
                        productInterest,
                        leadScore,
                        priorityRank,
                        campaignId: campaignId || null,
                        status: "NEW",
                        aiSummary: `Inbound enquiry from ${sourceChannel} for ${productInterest}. Auto-scored as Priority ${priorityRank} (${leadScore}/100).`
                    }
                });

                // Also push directly into Core Lead Database (Customer Finding Intelligence)
                try {
                    const coreLead = await prisma.lead.create({
                        data: {
                            guestName: fullName,
                            guestPhone: phone.trim(),
                            guestEmail: email || null,
                            area: location,
                            serviceType: customerType === "RETAILER" ? "retailer" : customerType === "DOCTOR" ? "doctor" : "direct",
                            source: `marketing_${sourceChannel.toLowerCase()}`,
                            status: "new",
                            details: `Inbound lead from AI Marketing Campaign (${productInterest}). Score: ${leadScore}, Priority: ${priorityRank}`,
                            qualityScore: leadScore,
                            tags: ["marketing_inbound", priorityRank, sourceChannel]
                        }
                    });

                    // Link back the core lead ID
                    await prisma.marketingLead.update({
                        where: { id: savedLead.id },
                        data: { linkedLeadId: coreLead.id }
                    });
                } catch (linkErr) {
                    console.error("Core Lead linking error (non-fatal):", linkErr.message);
                }
            }

            return NextResponse.json({
                success: true,
                message: `Lead captured and integrated with Customer Finding Intelligence. Assigned Priority Tier: ${priorityRank}`,
                lead: savedLead
            });
        }

        // =====================================================================
        // ACTION 5: RETARGETING AUDIENCE BUILDER
        // =====================================================================
        if (action === "build_retargeting_audience") {
            const { segmentType = "CHRONIC_REFILL_DUE" } = body;

            // Generate high-intent audience lists based on customer behavior
            let audienceResults = [];

            if (segmentType === "CHRONIC_REFILL_DUE") {
                // Find real customers whose last order was 25-35 days ago
                const daysAgo35 = new Date();
                daysAgo35.setDate(daysAgo35.getDate() - 35);
                const daysAgo25 = new Date();
                daysAgo25.setDate(daysAgo25.getDate() - 25);

                const refillDueOrders = await prisma.order.findMany({
                    where: {
                        createdAt: { gte: daysAgo35, lte: daysAgo25 },
                        status: { in: ["DELIVERED", "COMPLETED"] }
                    },
                    include: { user: { select: { name: true, phone: true } } },
                    take: 20
                });

                audienceResults = refillDueOrders.map(o => ({
                    name: o.user?.name || o.customerName || "Customer",
                    phone: o.user?.phone || o.phone || "",
                    reason: `Order #${o.id?.slice(-6)} delivered ~${Math.floor((Date.now() - new Date(o.createdAt)) / 86400000)} days ago — refill due`,
                    priority: "A"
                })).filter(a => a.phone);
            } else if (segmentType === "CART_DROP_OFF") {
                // Find real carts abandoned in last 24 hours
                const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
                const cartDropOffs = await prisma.lead.findMany({
                    where: {
                        serviceType: "cart_abandoned",
                        createdAt: { gte: oneDayAgo }
                    },
                    take: 20
                });
                audienceResults = cartDropOffs.map(l => ({
                    name: l.guestName || "Customer",
                    phone: l.guestPhone || "",
                    reason: `Abandoned cart — ${l.notes || "high-intent items added"}`,
                    priority: "A"
                })).filter(a => a.phone);
            } else {
                // VIDEO_ENGAGED: find leads from video/social channels with high score
                const videoLeads = await prisma.marketingLead.findMany({
                    where: { sourceChannel: { in: ["YOUTUBE", "INSTAGRAM"] }, leadScore: { gte: 70 } },
                    take: 20
                });
                audienceResults = videoLeads.map(l => ({
                    name: l.fullName || "Customer",
                    phone: l.phone || "",
                    reason: `High engagement via ${l.sourceChannel} — Lead Score ${l.leadScore}/100`,
                    priority: l.priorityRank || "B"
                })).filter(a => a.phone);
            }

            return NextResponse.json({
                success: true,
                segmentType,
                count: audienceResults.length,
                audiences: audienceResults,
                recommendedCampaign: `Automated WhatsApp Retargeting Offer with 10% Discount Code`
            });
        }

        return NextResponse.json({ error: "Invalid action specified." }, { status: 400 });
    } catch (error) {
        console.error("Marketing Intelligence POST Error:", error);
        return NextResponse.json({ error: "Failed to process marketing intelligence action." }, { status: 500 });
    }
}
