import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(req) {
    const { searchParams } = new URL(req.url);
    const category = searchParams.get('category');
    const search = searchParams.get('search');
    const runFix = searchParams.get('fix') === 'true';

    // --- NINJA DB REMEDIATION START ---
    let remediationLogs = [];
    if (runFix) {
        const statements = [
            `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isOTC" BOOLEAN DEFAULT false`,
            `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isScheduleH1" BOOLEAN DEFAULT false`,
            `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isColdChain" BOOLEAN DEFAULT false`,
            `ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneVerified" BOOLEAN DEFAULT false`,
            `ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastIpAddress" TEXT`,
            `ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deviceId" TEXT`,
            `CREATE TABLE IF NOT EXISTS "SubOrder" ( "id" TEXT PRIMARY KEY, "orderId" TEXT, "retailerId" TEXT, "userId" TEXT, "items" JSONB, "total" DOUBLE PRECISION, "status" TEXT DEFAULT 'Pending', "createdAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "DraftInvoice" ( "id" TEXT PRIMARY KEY, "subOrderId" TEXT, "amount" DOUBLE PRECISION, "status" TEXT DEFAULT 'Pending', "isAutoGenerated" BOOLEAN DEFAULT false, "createdAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "MedicinePriceMemory" ( "id" TEXT PRIMARY KEY, "medicineName" TEXT UNIQUE, "price" DOUBLE PRECISION, "updatedAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "SubstitutionRule" ( "id" TEXT PRIMARY KEY, "sourceMedicine" TEXT UNIQUE, "substituteGeneric" TEXT, "isActive" BOOLEAN DEFAULT true, "createdAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "DeliveryAssignment" ( "id" TEXT PRIMARY KEY, "orderId" TEXT, "agentId" TEXT, "status" TEXT DEFAULT 'Assigned', "assignedAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "WebhookConfig" ( "id" TEXT PRIMARY KEY, "url" TEXT, "events" TEXT[], "isActive" BOOLEAN DEFAULT true, "createdAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "AdminApprovalLog" ( "id" TEXT PRIMARY KEY, "adminId" TEXT, "actionType" TEXT, "targetId" TEXT, "createdAt" TIMESTAMP DEFAULT NOW() )`
        ];

        for (const sql of statements) {
            try {
                await prisma.$executeRawUnsafe(sql);
                remediationLogs.push({ sql, status: 'success' });
            } catch (e) {
                remediationLogs.push({ sql, status: 'error', message: e.message });
            }
        }

        // If we only wanted the fix, return the logs
        if (searchParams.get('onlyfix') === 'true') {
            return NextResponse.json({ success: true, logs: remediationLogs });
        }
    }
    // --- NINJA DB REMEDIATION END ---

    try {
        const where = {};
        if (category && category !== 'All') {
            where.category = category;
        }
        if (search) {
            where.OR = [
                { name: { contains: search, mode: 'insensitive' } },
                { description: { contains: search, mode: 'insensitive' } }
            ];
        }

        let products = await prisma.product.findMany({
            where,
            orderBy: { createdAt: 'desc' },
            take: 20
        });

        // --- SELF-HEALING SEED START ---
        // If the database is empty, automatically seed it with real medicines
        if (products.length === 0 && !category && !search) {
            const seedProducts = [
                { name: "Dolo 650", description: "Paracetamol 650mg. Rapid relief from fever and pain.", price: 30.50, image: "https://images.unsplash.com/photo-1584308666744-24d59b298f0d?auto=format&fit=crop&w=400&q=80", category: "General", requiresPrescription: false, stock: 150, uses: "Fever, Body Ache", sideEffects: "Nausea" },
                { name: "Calpol 500", description: "Paracetamol 500mg. Highly effective for fever reduction.", price: 15.00, image: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=400&q=80", category: "General", requiresPrescription: false, stock: 85, uses: "Fever, Low-grade Pain" },
                { name: "Combiflam", description: "Ibuprofen + Paracetamol. Powerful dual-action for body aches.", price: 45.20, image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=400&q=80", category: "Pain Relief", requiresPrescription: false, stock: 200, uses: "Body Pain, Headache", sideEffects: "Acidity" },
                { name: "Augmentin 625 Duo", description: "Broad-spectrum antibiotic for bacterial infections.", price: 201.75, image: "https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=400&q=80", category: "Antibiotics", requiresPrescription: true, stock: 35, uses: "Infections" },
                { name: "Zincovit Tablet", description: "Multi-vitamin supplement for daily immunity.", price: 105.00, image: "https://images.unsplash.com/photo-1550572017-edb9215037d0?auto=format&fit=crop&w=400&q=80", category: "Supplements", requiresPrescription: false, stock: 500, uses: "Immunity Booster" },
                { name: "Himalaya Liv.52", description: "Herbal formula for liver protection.", price: 155.00, image: "https://images.unsplash.com/photo-1550572017-edb9215037d0?auto=format&fit=crop&w=400&q=80", category: "Ayurvedic", requiresPrescription: false, stock: 120, uses: "Liver Health" }
            ];
            await prisma.product.createMany({ data: seedProducts });
            products = await prisma.product.findMany({ take: 20, orderBy: { createdAt: 'desc' } });
        }
        // --- SELF-HEALING SEED END ---

        return NextResponse.json({ success: true, products, fixed: runFix, logs: runFix ? remediationLogs : undefined });
    } catch (error) {
        return NextResponse.json({
            success: false,
            error: error.message,
            remediationAttempted: runFix,
            logs: remediationLogs.length > 0 ? remediationLogs : undefined
        }, { status: 500 });
    }
}
