import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(req) {
    const { searchParams } = new URL(req.url);
    const category = searchParams.get('category');
    const search = searchParams.get('search');
    const runFix = searchParams.get('fix') === 'true';

    // --- NINJA DB REMEDIATION START ---
    let remediationLogs = [];
    if (runFix) {
        const statements = [
            `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isOTC" BOOLEAN DEFAULT false`,
            `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isScheduleH1" BOOLEAN DEFAULT false`,
            `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isColdChain" BOOLEAN DEFAULT false`,
            `ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneVerified" BOOLEAN DEFAULT false`,
            `ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastIpAddress" TEXT`,
            `ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deviceId" TEXT`,
            `CREATE TABLE IF NOT EXISTS "SubOrder" ( "id" TEXT PRIMARY KEY, "orderId" TEXT, "retailerId" TEXT, "userId" TEXT, "items" JSONB, "total" DOUBLE PRECISION, "status" TEXT DEFAULT 'Pending', "createdAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "DraftInvoice" ( "id" TEXT PRIMARY KEY, "subOrderId" TEXT, "amount" DOUBLE PRECISION, "status" TEXT DEFAULT 'Pending', "isAutoGenerated" BOOLEAN DEFAULT false, "createdAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "MedicinePriceMemory" ( "id" TEXT PRIMARY KEY, "medicineName" TEXT UNIQUE, "price" DOUBLE PRECISION, "updatedAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "SubstitutionRule" ( "id" TEXT PRIMARY KEY, "sourceMedicine" TEXT UNIQUE, "substituteGeneric" TEXT, "isActive" BOOLEAN DEFAULT true, "createdAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "DeliveryAssignment" ( "id" TEXT PRIMARY KEY, "orderId" TEXT, "agentId" TEXT, "status" TEXT DEFAULT 'Assigned', "assignedAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "WebhookConfig" ( "id" TEXT PRIMARY KEY, "url" TEXT, "events" TEXT[], "isActive" BOOLEAN DEFAULT true, "createdAt" TIMESTAMP DEFAULT NOW() )`,
            `CREATE TABLE IF NOT EXISTS "AdminApprovalLog" ( "id" TEXT PRIMARY KEY, "adminId" TEXT, "actionType" TEXT, "targetId" TEXT, "createdAt" TIMESTAMP DEFAULT NOW() )`
        ];

        for (const sql of statements) {
            try {
                await prisma.$executeRawUnsafe(sql);
                remediationLogs.push({ sql, status: 'success' });
            } catch (e) {
                remediationLogs.push({ sql, status: 'error', message: e.message });
            }
        }

        // If we only wanted the fix, return the logs
        if (searchParams.get('onlyfix') === 'true') {
            return NextResponse.json({ success: true, logs: remediationLogs });
        }
    }
    // --- NINJA DB REMEDIATION END ---

    try {
        const where = {};
        if (category && category !== 'All') {
            where.category = category;
        }
        if (search) {
            where.OR = [
                { name: { contains: search, mode: 'insensitive' } },
                { description: { contains: search, mode: 'insensitive' } }
            ];
        }

        const products = await prisma.product.findMany({
            where,
            orderBy: { createdAt: 'desc' },
            take: 20
        });

        return NextResponse.json({ success: true, products, fixed: runFix, logs: runFix ? remediationLogs : undefined });
    } catch (error) {
        return NextResponse.json({
            success: false,
            error: error.message,
            remediationAttempted: runFix,
            logs: remediationLogs.length > 0 ? remediationLogs : undefined
        }, { status: 500 });
    }
}
