import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

export async function POST(req) {
    const session = await getServerSession(authOptions);
    if (!session || session.user.role !== 'RETAILER') {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    try {
        const { orderId, tamperSealCode, retailerProcurementCost } = await req.json();

        if (!orderId || !tamperSealCode) {
            return NextResponse.json({ error: "Order ID and Seal Code are required" }, { status: 400 });
        }

        // 1. Verify the order belongs to this retailer and is in the correct status
        const order = await prisma.order.findUnique({
            where: { id: orderId }
        });

        if (!order) {
            return NextResponse.json({ error: "Order not found" }, { status: 404 });
        }

        if (order.status !== "Preparing") {
            return NextResponse.json({ error: "Order must be in 'Preparing' status to pack." }, { status: 400 });
        }

        // 2. Fetch Retailer to get agreed platform margin
        const retailer = await prisma.retailer.findUnique({
            where: { userId: session.user.id },
            select: { id: true, agreedPlatformMargin: true }
        });

        if (!retailer) {
            return NextResponse.json({ error: "Retailer profile not found" }, { status: 404 });
        }

        // 3. Update the Order status and seal code
        const updatedOrder = await prisma.order.update({
            where: { id: orderId },
            data: {
                status: "Ready_for_Pickup",
                tamperSealCode: tamperSealCode,
                integrityStatus: "PENDING"
            }
        });

        // 4. Generate SubOrder and DraftInvoice for Financial Ledger
        const customerTotal = order.total;
        const platformMarginPerc = retailer.agreedPlatformMargin || 10.0;
        const platformFee = (customerTotal * platformMarginPerc) / 100;
        const retailerAmount = customerTotal - platformFee;
        const procurementCost = retailerProcurementCost ? parseFloat(retailerProcurementCost) : null;

        // Ensure a SubOrder exists
        let subOrder = await prisma.subOrder.findFirst({
            where: { orderId: order.id, retailerId: retailer.id }
        });

        if (!subOrder) {
            subOrder = await prisma.subOrder.create({
                data: {
                    orderId: order.id,
                    retailerId: retailer.id,
                    userId: order.userId,
                    items: order.items || [], // Could fetch actual items if needed
                    total: customerTotal,
                    status: "Invoice_Generated"
                }
            });
        }

        // Upsert Draft Invoice
        const draftInvoice = await prisma.draftInvoice.create({
            data: {
                subOrderId: subOrder.id,
                amount: retailerAmount, // Legacy compatibility
                customerTotal: customerTotal,
                platformMarginPerc: platformMarginPerc,
                platformFee: platformFee,
                retailerAmount: retailerAmount,
                retailerProcurementCost: procurementCost,
                status: "Approved", // Auto-approved for standard process
                isAutoGenerated: true
            }
        });

        return NextResponse.json({
            success: true,
            message: "Order packed and invoice generated successfully. Ready for pickup.",
            order: updatedOrder,
            invoice: draftInvoice
        });

    } catch (error) {
        console.error("Packing API Error:", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
