/**
 * Role-Based Access Control (RBAC) System
 * Defines roles, permissions, and validation utilities.
 */

export const ROLES = {
    // Leadership
    SUPER_ADMIN: "SUPER_ADMIN", // Kaushlesh Mishra

    // Marketing
    MARKETING_MANAGER: "MARKETING_MANAGER",
    SOCIAL_MEDIA_EXECUTIVE: "SOCIAL_MEDIA_EXECUTIVE",
    DIGITAL_MARKETING_EXECUTIVE: "DIGITAL_MARKETING_EXECUTIVE",

    // Sales
    SALES_MANAGER: "SALES_MANAGER",
    CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
    ORDER_PROCESSING: "ORDER_PROCESSING",
    SALES_STAFF: "SALES_STAFF", // Generic fallback

    // Operations
    OPERATIONS_MANAGER: "OPERATIONS_MANAGER",
    PROCUREMENT_OFFICER: "PROCUREMENT_OFFICER",
    STORE_KEEPER: "STORE_KEEPER",
    DISPATCH_TEAM: "DISPATCH_TEAM",
    WAREHOUSE_STAFF: "WAREHOUSE_STAFF", // Generic fallback

    // Finance & Quality
    FINANCE_ACCOUNTS: "FINANCE_ACCOUNTS",
    PHARMACIST: "PHARMACIST",
    
    // External
    CUSTOMER: "CUSTOMER", // Default
};

export const ACTIONS = {
    // Super Admin Level
    MANAGE_SETTINGS: "MANAGE_SETTINGS",
    MANAGE_USERS: "MANAGE_USERS",
    MANAGE_PRICES_GLOBALLY: "MANAGE_PRICES_GLOBALLY",
    MANAGE_SOPS: "MANAGE_SOPS",
    HARD_DELETE_RECORDS: "HARD_DELETE_RECORDS",
    VIEW_ALL_REPORTS: "VIEW_ALL_REPORTS",
    EXPORT_DATABASE: "EXPORT_DATABASE",
    APPROVE_LARGE_REFUNDS: "APPROVE_LARGE_REFUNDS",
    MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",

    // Marketing
    MANAGE_CAMPAIGNS: "MANAGE_CAMPAIGNS",
    VIEW_ANALYTICS: "VIEW_ANALYTICS",
    UPDATE_SOCIAL_MEDIA: "UPDATE_SOCIAL_MEDIA",

    // Sales Manager & Support
    OVERSEE_SALES: "OVERSEE_SALES",
    VIEW_ALL_ORDERS: "VIEW_ALL_ORDERS",
    CREATE_ORDERS: "CREATE_ORDERS",
    VIEW_CUSTOMER_DETAILS: "VIEW_CUSTOMER_DETAILS",
    PRINT_INVOICES: "PRINT_INVOICES",
    CHECK_STOCK: "CHECK_STOCK",
    VIEW_CUSTOMER_ORDERS: "VIEW_CUSTOMER_ORDERS",
    UPDATE_SUPPORT_TICKETS: "UPDATE_SUPPORT_TICKETS",
    PROCESS_APPROVED_RETURNS: "PROCESS_APPROVED_RETURNS",

    // Operations Manager & Sub-teams
    PROCESS_ORDERS: "PROCESS_ORDERS",
    UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",
    ASSIGN_DELIVERIES: "ASSIGN_DELIVERIES",
    VIEW_INVENTORY: "VIEW_INVENTORY",
    GENERATE_REPORTS: "GENERATE_REPORTS",
    CREATE_PURCHASE_ORDERS: "CREATE_PURCHASE_ORDERS",
    VENDOR_MANAGEMENT: "VENDOR_MANAGEMENT",
    RECEIVE_STOCK: "RECEIVE_STOCK",
    DISPATCH_STOCK: "DISPATCH_STOCK",
    UPDATE_INVENTORY_QUANTITIES: "UPDATE_INVENTORY_QUANTITIES",
    UPDATE_DELIVERY_STATUS: "UPDATE_DELIVERY_STATUS",

    // Pharmacist
    VERIFY_PRESCRIPTIONS: "VERIFY_PRESCRIPTIONS",
    APPROVE_DISPENSING: "APPROVE_DISPENSING",
    UPDATE_MEDICINE_AVAILABILITY: "UPDATE_MEDICINE_AVAILABILITY",

    // Finance & Accounts
    MANAGE_FINANCES: "MANAGE_FINANCES",
    VIEW_REVENUE_REPORTS: "VIEW_REVENUE_REPORTS",
    PROCESS_PAYROLL: "PROCESS_PAYROLL",
};

/**
 * The Permissions Matrix
 * Defines exactly what actions each role is allowed to perform.
 */
export const PERMISSIONS = {
    [ROLES.SUPER_ADMIN]: Object.values(ACTIONS), // All access

    // --- MARKETING ---
    [ROLES.MARKETING_MANAGER]: [
        ACTIONS.MANAGE_CAMPAIGNS,
        ACTIONS.VIEW_ANALYTICS,
        ACTIONS.UPDATE_SOCIAL_MEDIA,
        ACTIONS.VIEW_ALL_REPORTS,
    ],
    [ROLES.SOCIAL_MEDIA_EXECUTIVE]: [
        ACTIONS.UPDATE_SOCIAL_MEDIA,
        ACTIONS.VIEW_ANALYTICS,
    ],
    [ROLES.DIGITAL_MARKETING_EXECUTIVE]: [
        ACTIONS.MANAGE_CAMPAIGNS,
        ACTIONS.VIEW_ANALYTICS,
    ],

    // --- SALES ---
    [ROLES.SALES_MANAGER]: [
        ACTIONS.OVERSEE_SALES,
        ACTIONS.VIEW_ALL_ORDERS,
        ACTIONS.GENERATE_REPORTS,
        ACTIONS.VIEW_CUSTOMER_DETAILS,
    ],
    [ROLES.CUSTOMER_SUPPORT]: [
        ACTIONS.VIEW_CUSTOMER_ORDERS,
        ACTIONS.UPDATE_SUPPORT_TICKETS,
        ACTIONS.PROCESS_APPROVED_RETURNS,
        ACTIONS.VIEW_CUSTOMER_DETAILS,
    ],
    [ROLES.ORDER_PROCESSING]: [
        ACTIONS.PROCESS_ORDERS,
        ACTIONS.UPDATE_ORDER_STATUS,
        ACTIONS.CREATE_ORDERS,
        ACTIONS.PRINT_INVOICES,
    ],
    [ROLES.SALES_STAFF]: [
        ACTIONS.CREATE_ORDERS,
        ACTIONS.VIEW_CUSTOMER_DETAILS,
        ACTIONS.PRINT_INVOICES,
        ACTIONS.CHECK_STOCK,
    ],

    // --- OPERATIONS ---
    [ROLES.OPERATIONS_MANAGER]: [
        ACTIONS.PROCESS_ORDERS,
        ACTIONS.UPDATE_ORDER_STATUS,
        ACTIONS.ASSIGN_DELIVERIES,
        ACTIONS.VIEW_INVENTORY,
        ACTIONS.GENERATE_REPORTS,
        ACTIONS.VIEW_CUSTOMER_DETAILS,
        ACTIONS.VENDOR_MANAGEMENT,
    ],
    [ROLES.PROCUREMENT_OFFICER]: [
        ACTIONS.CREATE_PURCHASE_ORDERS,
        ACTIONS.VENDOR_MANAGEMENT,
        ACTIONS.VIEW_INVENTORY,
    ],
    [ROLES.STORE_KEEPER]: [
        ACTIONS.RECEIVE_STOCK,
        ACTIONS.DISPATCH_STOCK,
        ACTIONS.UPDATE_INVENTORY_QUANTITIES,
        ACTIONS.CHECK_STOCK,
        ACTIONS.VIEW_INVENTORY,
    ],
    [ROLES.DISPATCH_TEAM]: [
        ACTIONS.ASSIGN_DELIVERIES,
        ACTIONS.UPDATE_DELIVERY_STATUS,
        ACTIONS.VIEW_CUSTOMER_DETAILS, // Need addresses
    ],
    [ROLES.WAREHOUSE_STAFF]: [
        ACTIONS.RECEIVE_STOCK,
        ACTIONS.DISPATCH_STOCK,
        ACTIONS.UPDATE_INVENTORY_QUANTITIES,
        ACTIONS.CHECK_STOCK,
        ACTIONS.VIEW_INVENTORY,
    ],

    // --- FINANCE & ACCOUNTS ---
    [ROLES.FINANCE_ACCOUNTS]: [
        ACTIONS.MANAGE_FINANCES,
        ACTIONS.VIEW_REVENUE_REPORTS,
        ACTIONS.PROCESS_PAYROLL,
        ACTIONS.VIEW_ALL_ORDERS,
        ACTIONS.VIEW_ALL_REPORTS,
    ],

    // --- PHARMACY ---
    [ROLES.PHARMACIST]: [
        ACTIONS.VERIFY_PRESCRIPTIONS,
        ACTIONS.APPROVE_DISPENSING,
        ACTIONS.UPDATE_MEDICINE_AVAILABILITY,
        ACTIONS.VIEW_INVENTORY,
    ],

    [ROLES.CUSTOMER]: [
        // Customers don't have back-office admin permissions
    ],
};

/**
 * Check if a user role has permission to perform a specific action.
 * @param {string} role - The role of the user (e.g. from session.user.role)
 * @param {string} action - The action from ACTIONS
 * @returns {boolean}
 */
export function hasPermission(role, action) {
    if (!role) return false;
    
    // Legacy support for "ADMIN" role acting as SUPER_ADMIN temporarily
    if (role === "ADMIN" || role === ROLES.SUPER_ADMIN) {
        return true; 
    }

    const rolePermissions = PERMISSIONS[role];
    if (!rolePermissions) return false;

    return rolePermissions.includes(action);
}

/**
 * Get all available roles for UI dropdowns
 */
export function getAvailableRoles() {
    return Object.values(ROLES);
}
