import prisma from "@/lib/prisma";
import { WhatsAppTriggers } from "@/lib/whatsapp";

/**
 * Service to automatically generate draft invoices if a retailer is delayed.
 * This can be called by a cron job or a background worker.
 */
export async function autoGenerateDelayedInvoices() {
    console.log("[INVOICE SERVICE] Checking for delayed retailer invoices...");

    try {
        const tenMinutesAgo = new Date(Date.now() - 10 * 60 * 1000);

        // 1. Find SubOrders that are "Invoice_Pending" and created more than 10 mins ago
        // and don't already have a DraftInvoice
        const delayedSubOrders = await prisma.subOrder.findMany({
            where: {
                status: "Invoice_Pending",
                createdAt: { lt: tenMinutesAgo },
                draftInvoices: { none: {} }
            },
            include: { retailer: true, order: true }
        });

        console.log(`[INVOICE SERVICE] Found ${delayedSubOrders.length} delayed sub-orders.`);

        for (const subOrder of delayedSubOrders) {
            // 2. Auto-generate Draft Invoice
            const draftInvoice = await prisma.draftInvoice.create({
                data: {
                    subOrderId: subOrder.id,
                    amount: subOrder.total,
                    status: "Pending",
                    isAutoGenerated: true,
                    adminRemarks: "Auto-generated due to retailer delay (10 min timeout)."
                }
            });

            // 3. Notify Admin
            await WhatsAppTriggers.invoicePending("9161364908", 1);

            // 4. Notify Retailer of the bypass
            if (subOrder.retailer.phone) {
                await WhatsAppTriggers.invoiceReminder(subOrder.retailer.phone, subOrder.id);
            }

            console.log(`[INVOICE SERVICE] Auto-generated invoice ${draftInvoice.id} for SubOrder ${subOrder.id}`);
        }

    } catch (error) {
        console.error("[INVOICE SERVICE ERROR] Failed to generate invoices:", error);
    }
}

/**
 * Logic to learn price corrections from admin edits
 */
export async function learnPriceFromInvoice(draftInvoiceId) {
    try {
        const invoice = await prisma.draftInvoice.findUnique({
            where: { id: draftInvoiceId },
            include: { subOrder: true }
        });

        if (!invoice || invoice.status !== "Approved") return;

        // Iterate through items in the sub-order and update price memory
        const items = invoice.subOrder.items; // JSON array
        for (const item of items) {
            await prisma.medicinePriceMemory.upsert({
                where: { medicineName: item.name },
                update: {
                    price: item.price,
                    lastRetailerId: invoice.subOrder.retailerId
                },
                create: {
                    medicineName: item.name,
                    price: item.price,
                    lastRetailerId: invoice.subOrder.retailerId
                }
            });
        }

        console.log(`[PRICE LEARNING] Learned prices from Invoice ${invoice.id}`);

    } catch (error) {
        console.error("[PRICE LEARNING ERROR] Failed to learn prices:", error);
    }
}
