export const generateTallyXML = (orders) => {
    let xml = `<!-- XML generated by Swastik Medicare -->
<ENVELOPE>
    <HEADER>
        <TALLYREQUEST>Import Data</TALLYREQUEST>
    </HEADER>
    <BODY>
        <IMPORTDATA>
            <REQUESTDESC>
                <REPORTNAME>Vouchers</REPORTNAME>
                <STATICVARIABLES>
                    <SVCURRENTCOMPANY>Swastik Medicare</SVCURRENTCOMPANY>
                </STATICVARIABLES>
            </REQUESTDESC>
            <REQUESTDATA>`;

    orders.forEach(order => {
        // Format date to YYYYMMDD
        const dateObj = new Date(order.date);
        const dateStr = dateObj.toISOString().slice(0, 10).replace(/-/g, "");

        // Determine Party Name (Ledger in Tally)
        // Ensure this Ledger exists in Tally or use a suspense account
        const partyName = order.customer ? order.customer.replace(/&/g, "&amp;") : "Cash Provider";

        xml += `
                <TALLYMESSAGE xmlns:UDF="TallyUDF">
                    <VOUCHER VCHTYPE="Sales" ACTION="Create" OBJVIEW="Accounting Voucher View">
                        <DATE>${dateStr}</DATE>
                        <NARRATION>Order ID: ${order.id} - ${order.items.replace(/&/g, "&amp;")}</NARRATION>
                        <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
                        <VOUCHERNUMBER>${order.id.slice(-6)}</VOUCHERNUMBER>
                        <PARTYLEDGERNAME>${partyName}</PARTYLEDGERNAME>
                        <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
                        <PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>
                        
                        <!-- Party Ledger Entry (Debit) -->
                        <ALLLEDGERENTRIES.LIST>
                            <LEDGERNAME>${partyName}</LEDGERNAME>
                            <ISDEEMEDPOSITIVE>Bs</ISDEEMEDPOSITIVE>
                            <LEDGERFROMITEM>No</LEDGERFROMITEM>
                            <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
                            <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
                            <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
                            <AMOUNT>-${order.total}</AMOUNT>
                        </ALLLEDGERENTRIES.LIST>

                        <!-- Sales Ledger Entry (Credit) -->
                        <ALLLEDGERENTRIES.LIST>
                            <LEDGERNAME>Sales Account</LEDGERNAME>
                            <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
                            <LEDGERFROMITEM>No</LEDGERFROMITEM>
                            <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
                            <ISPARTYLEDGER>No</ISPARTYLEDGER>
                            <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
                            <AMOUNT>${order.total}</AMOUNT>
                        </ALLLEDGERENTRIES.LIST>
                    </VOUCHER>
                </TALLYMESSAGE>`;
    });

    xml += `
            </REQUESTDATA>
        </IMPORTDATA>
    </BODY>
</ENVELOPE>`;

    return xml;
};
