import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../../auth/[...nextauth]/route";

/**
 * PRODUCTION DATABASE REMEDIATION API
 * This is a one-time use route to sync the production database schema
 * with the new marketplace features.
 */

export async function GET(req) {
    try {
        // Simple security check: Only allow if a specific secret is provided in query
        // or if the user is an ADMIN (though session might not be established if DB is broken).
        const { searchParams } = new URL(req.url);
        const secret = searchParams.get("secret");

        // Use a temporary hardcoded secret for this one-time fix
        if (secret !== "swastik_remediate_2026") {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        console.log("[REMEDIATION] Starting SQL execution...");

        const sql = `
            -- Marketplace Remediation
            DO $$ 
            BEGIN 
                -- Add Product columns
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isOTC') THEN
                    ALTER TABLE "Product" ADD COLUMN "isOTC" BOOLEAN DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isScheduleH1') THEN
                    ALTER TABLE "Product" ADD COLUMN "isScheduleH1" BOOLEAN DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isColdChain') THEN
                    ALTER TABLE "Product" ADD COLUMN "isColdChain" BOOLEAN DEFAULT false;
                END IF;
                
                -- Add User columns
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='phoneVerified') THEN
                    ALTER TABLE "User" ADD COLUMN "phoneVerified" BOOLEAN DEFAULT false;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS "SubOrder" (
                "id" TEXT NOT NULL,
                "orderId" TEXT NOT NULL,
                "retailerId" TEXT NOT NULL,
                "userId" TEXT,
                "items" JSONB NOT NULL,
                "total" DOUBLE PRECISION NOT NULL,
                "status" TEXT NOT NULL DEFAULT 'Pending',
                "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updatedAt" TIMESTAMP(3) NOT NULL,
                CONSTRAINT "SubOrder_pkey" PRIMARY KEY ("id")
            );

            CREATE TABLE IF NOT EXISTS "DraftInvoice" (
                "id" TEXT NOT NULL,
                "subOrderId" TEXT NOT NULL,
                "amount" DOUBLE PRECISION NOT NULL,
                "status" TEXT NOT NULL DEFAULT 'Pending',
                "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
                "adminRemarks" TEXT,
                "rejectionReason" TEXT,
                "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updatedAt" TIMESTAMP(3) NOT NULL,
                CONSTRAINT "DraftInvoice_pkey" PRIMARY KEY ("id")
            );

            CREATE TABLE IF NOT EXISTS "MedicinePriceMemory" (
                "id" TEXT NOT NULL,
                "medicineName" TEXT NOT NULL,
                "genericName" TEXT,
                "price" DOUBLE PRECISION NOT NULL,
                "lastRetailerId" TEXT,
                "updatedAt" TIMESTAMP(3) NOT NULL,
                CONSTRAINT "MedicinePriceMemory_pkey" PRIMARY KEY ("id")
            );

            CREATE TABLE IF NOT EXISTS "SubstitutionRule" (
                "id" TEXT NOT NULL,
                "sourceMedicine" TEXT NOT NULL,
                "substituteGeneric" TEXT NOT NULL,
                "isActive" BOOLEAN NOT NULL DEFAULT true,
                "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "SubstitutionRule_pkey" PRIMARY KEY ("id")
            );

            CREATE TABLE IF NOT EXISTS "DeliveryAssignment" (
                "id" TEXT NOT NULL,
                "orderId" TEXT NOT NULL,
                "agentId" TEXT NOT NULL,
                "status" TEXT NOT NULL DEFAULT 'Assigned',
                "distance" DOUBLE PRECISION,
                "estimatedTime" TEXT,
                "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updatedAt" TIMESTAMP(3) NOT NULL,
                CONSTRAINT "DeliveryAssignment_pkey" PRIMARY KEY ("id")
            );

            CREATE TABLE IF NOT EXISTS "WebhookConfig" (
                "id" TEXT NOT NULL,
                "url" TEXT NOT NULL,
                "secret" TEXT,
                "events" TEXT[],
                "isActive" BOOLEAN NOT NULL DEFAULT true,
                "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "WebhookConfig_pkey" PRIMARY KEY ("id")
            );

            CREATE TABLE IF NOT EXISTS "AdminApprovalLog" (
                "id" TEXT NOT NULL,
                "adminId" TEXT NOT NULL,
                "actionType" TEXT NOT NULL,
                "targetId" TEXT NOT NULL,
                "details" TEXT,
                "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "AdminApprovalLog_pkey" PRIMARY KEY ("id")
            );
        `;

        // Execute SQL logic in parts if needed, but since it's raw we try the whole string
        // We'll split by it because some drivers don't like multiple statements
        const statements = sql
            .split(';')
            .map(s => s.trim())
            .filter(s => s.length > 0);

        for (const statement of statements) {
            await prisma.$executeRawUnsafe(statement);
        }

        console.log("[REMEDIATION] Success.");

        return NextResponse.json({
            success: true,
            message: "Production database schema has been successfully remediated."
        });

    } catch (error) {
        console.error("[REMEDIATION ERROR]", error);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
