import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(req) {
    console.log("[FIX-DB] API TRIGERRED");
    try {
        const { searchParams } = new URL(req.url);
        const secret = searchParams.get("secret");

        if (secret !== "swastik_fix_2026") {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const sql = `
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isOTC') THEN
                    ALTER TABLE "Product" ADD COLUMN "isOTC" BOOLEAN DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isScheduleH1') THEN
                    ALTER TABLE "Product" ADD COLUMN "isScheduleH1" BOOLEAN DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isColdChain') THEN
                    ALTER TABLE "Product" ADD COLUMN "isColdChain" BOOLEAN DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='phoneVerified') THEN
                    ALTER TABLE "User" ADD COLUMN "phoneVerified" BOOLEAN DEFAULT false;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS "SubOrder" ( "id" TEXT PRIMARY KEY, "orderId" TEXT, "retailerId" TEXT, "userId" TEXT, "items" JSONB, "total" DOUBLE PRECISION, "status" TEXT DEFAULT 'Pending', "createdAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() );
            CREATE TABLE IF NOT EXISTS "DraftInvoice" ( "id" TEXT PRIMARY KEY, "subOrderId" TEXT, "amount" DOUBLE PRECISION, "status" TEXT DEFAULT 'Pending', "isAutoGenerated" BOOLEAN DEFAULT false, "adminRemarks" TEXT, "rejectionReason" TEXT, "createdAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() );
            CREATE TABLE IF NOT EXISTS "MedicinePriceMemory" ( "id" TEXT PRIMARY KEY, "medicineName" TEXT UNIQUE, "genericName" TEXT, "price" DOUBLE PRECISION, "lastRetailerId" TEXT, "updatedAt" TIMESTAMP DEFAULT NOW() );
            CREATE TABLE IF NOT EXISTS "SubstitutionRule" ( "id" TEXT PRIMARY KEY, "sourceMedicine" TEXT UNIQUE, "substituteGeneric" TEXT, "isActive" BOOLEAN DEFAULT true, "createdAt" TIMESTAMP DEFAULT NOW() );
            CREATE TABLE IF NOT EXISTS "DeliveryAssignment" ( "id" TEXT PRIMARY KEY, "orderId" TEXT, "agentId" TEXT, "status" TEXT DEFAULT 'Assigned', "distance" DOUBLE PRECISION, "estimatedTime" TEXT, "assignedAt" TIMESTAMP DEFAULT NOW(), "updatedAt" TIMESTAMP DEFAULT NOW() );
            CREATE TABLE IF NOT EXISTS "WebhookConfig" ( "id" TEXT PRIMARY KEY, "url" TEXT, "secret" TEXT, "events" TEXT[], "isActive" BOOLEAN DEFAULT true, "createdAt" TIMESTAMP DEFAULT NOW() );
            CREATE TABLE IF NOT EXISTS "AdminApprovalLog" ( "id" TEXT PRIMARY KEY, "adminId" TEXT, "actionType" TEXT, "targetId" TEXT, "details" TEXT, "createdAt" TIMESTAMP DEFAULT NOW() );
        `;

        const statements = sql.split(';').map(s => s.trim()).filter(s => s.length > 0);
        for (const statement of statements) {
            await prisma.$executeRawUnsafe(statement);
        }

        return NextResponse.json({ success: true, message: "DB Remediated" });
    } catch (error) {
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
