import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(req) {
    const { searchParams } = new URL(req.url);
    const secret = searchParams.get("secret");

    if (secret !== "swastik_ninja_fix_2026") {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    try {
        const sql = `
            DO $$ 
            BEGIN 
                -- Product fixes
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isOTC') THEN
                    ALTER TABLE "Product" ADD COLUMN "isOTC" BOOLEAN DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isScheduleH1') THEN
                    ALTER TABLE "Product" ADD COLUMN "isScheduleH1" BOOLEAN DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Product' AND column_name='isColdChain') THEN
                    ALTER TABLE "Product" ADD COLUMN "isColdChain" BOOLEAN DEFAULT false;
                END IF;
                
                -- User fixes
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='phoneVerified') THEN
                    ALTER TABLE "User" ADD COLUMN "phoneVerified" BOOLEAN DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='lastIpAddress') THEN
                    ALTER TABLE "User" ADD COLUMN "lastIpAddress" TEXT;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='deviceId') THEN
                    ALTER TABLE "User" ADD COLUMN "deviceId" TEXT;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS "SubOrder" ( "id" TEXT PRIMARY KEY, "orderId" TEXT, "retailerId" TEXT, "userId" TEXT, "items" JSONB, "total" DOUBLE PRECISION, "status" TEXT DEFAULT 'Pending' );
            CREATE TABLE IF NOT EXISTS "DraftInvoice" ( "id" TEXT PRIMARY KEY, "subOrderId" TEXT, "amount" DOUBLE PRECISION, "status" TEXT DEFAULT 'Pending', "isAutoGenerated" BOOLEAN DEFAULT false );
            CREATE TABLE IF NOT EXISTS "MedicinePriceMemory" ( "id" TEXT PRIMARY KEY, "medicineName" TEXT UNIQUE, "price" DOUBLE PRECISION );
            CREATE TABLE IF NOT EXISTS "SubstitutionRule" ( "id" TEXT PRIMARY KEY, "sourceMedicine" TEXT UNIQUE, "substituteGeneric" TEXT );
            CREATE TABLE IF NOT EXISTS "DeliveryAssignment" ( "id" TEXT PRIMARY KEY, "orderId" TEXT, "agentId" TEXT, "status" TEXT DEFAULT 'Assigned' );
            CREATE TABLE IF NOT EXISTS "WebhookConfig" ( "id" TEXT PRIMARY KEY, "url" TEXT, "events" TEXT[] );
            CREATE TABLE IF NOT EXISTS "AdminApprovalLog" ( "id" TEXT PRIMARY KEY, "adminId" TEXT, "actionType" TEXT, "targetId" TEXT );
            
            DO $$ BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='SubOrder' AND column_name='createdAt') THEN
                    ALTER TABLE "SubOrder" ADD COLUMN "createdAt" TIMESTAMP DEFAULT NOW();
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='SubOrder' AND column_name='updatedAt') THEN
                    ALTER TABLE "SubOrder" ADD COLUMN "updatedAt" TIMESTAMP DEFAULT NOW();
                END IF;
            END $$;
        `;

        const statements = sql.split(';').map(s => s.trim()).filter(s => s.length > 0);
        for (const statement of statements) {
            await prisma.$executeRawUnsafe(statement);
        }

        return NextResponse.json({ success: true, message: "Production Database Sync Successful." });
    } catch (error) {
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
